name: DeployAzureFunction
variables:
  AzureConnection: 'DevOps Connection'
  ResourcegGroupName: 'connerDevOps'
  FunctionAppName: "functionappcicd98765"

trigger:
  branches:
    include:
    - '*' 



stages:
- stage: Build
  jobs:
  - job: Test_FA
    pool:
      vmImage: windows-2019
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Test ARM Deployment'
      inputs:
        azureSubscription: $(AzureConnection)
        resourceGroupName: $(ResourcegGroupName)
        location: 'eastus2'
        csmFile: Infrastructure/deploy_function_app.json
        csmParametersFile: Infrastructure/deploy_function_app_parameters.json
        deploymentMode: Validation
    - powershell: |
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
        Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
      displayName: 'Install Pester and import module'
    - powershell: |
        $outputFile = ".\testResults.xml"
        Invoke-Pester -OutputFile $outputFile -OutputFormat NUnitXml -enableExit
      failOnStderr: false
      displayName: 'Invoke-Pester'
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testRunTitle: 'Test Results for Pester'
        buildPlatform: 'Windows'
        testRunner: 'NUnit'
        testResultsFiles: './testResults.xml'
        failTaskOnFailedTests: true 
  - job: Build_FA
    pool:
      vmImage: windows-2019
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FunctionApp'
      inputs:
        rootFolderOrFile: FunctionApp
        includeRootFolder: false
        archiveFile: '$(System.DefaultWorkingDirectory)/zip/FunctionApp.zip'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'


- stage: Deploy
  condition:
    and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
    Build
  jobs:
  - job: Deploy_ARM
    pool:
      vmImage: windows-2019
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy Function App Resources'
      inputs:
        azureSubscription: $(AzureConnection)
        resourceGroupName: $(ResourcegGroupName)
        location: 'eastus2'
        csmFile: Infrastructure/deploy_function_app.json
        csmParametersFile: Infrastructure/deploy_function_app_parameters.json
        deploymentMode: Incremental
        deploymentOutputs: DeploymentOutput
    - task: AzurePowerShell@5
      displayName: 'Set FA Permissions'
      inputs:
        azureSubscription: $(AzureConnection)
        ScriptPath: Infrastructure/setSecurity.ps1
        ScriptArguments: 
          -subId c2c6e684-985c-4a2e-98ea-128c6d48609b
        azurePowerShellVersion: LatestVersion     
  - job: Deploy_FA
    dependsOn:
      Deploy_ARM
    pool:
      vmImage: windows-2019
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'zip'
        targetPath: '$(System.DefaultWorkingDirectory)/zip'
    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function'
      inputs:
        azureSubscription: $(AzureConnection)
        appType: functionApp
        appName: $(FunctionAppName)
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'auto'
